### ISSUE TITLE
Dospert

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#268] opened 2016-02-17 19:36 UTC
1) Tiny radio buttons.
2) Next button in middle of first screen, sends to bottom of next screen.
![dosbert_eb_next](https://cloud.githubusercontent.com/assets/17258830/13122159/adcd91d0-d583-11e5-979d-36ed092b9164.jpg)
3) Progress bar cuts off a bit of last set of responses.
![dospert_rp progress bar](https://cloud.githubusercontent.com/assets/17258830/13122162/b2c89284-d583-11e5-9261-1b1d18a575bc.jpg)

**Comment by zenkavi** [comment] 2016-02-18 16:02
So the next button appears at the bottom of the place after the first page? I tried experimenting a little with IE yesterday and even in the first page when I went back and forth between pages or when I opened the developer tools it would somehow move down to the end of the page. Has this been your experience as well? I'm trying to debug this issue but having a bit of a trouble..

**Comment by magvt** [comment] 2016-02-18 16:23
Yes, the next button works after the first screen. On the first screen, if you just click into each response, it remains in the same place.  But tabbing or hitting OK on the error msg re: not answering all qxs – then it goes to the bottom of the first screen.
But always sends me to the bottom of the next screen, so I need to scroll up.

**Comment by zenkavi** [comment] 2016-02-18 22:02
I fixed the scrolling issue in a pull request to another repo (with the core code for structuring experiments) . It won't be reflected in the version of the tasks you are taking right now (we will update all of them later) but you can feel free to stop listing that issue.

As for the other next button issues (popping up on random places on the page upon initial loading): I'm still working on them but I have found some indications that the specific html feature we are using for the questionnaires (flex boxes) to keep their aesthetic consistent with the other experiments (i.e. gray outer box + white inner box where the content is displayed) [might not be compatible with IE 11](https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview) in which case unless I find a hack around it we might simply have to advise our participants not to use IE. Since neither @tnsgmddb has reported it yet on firefox nor have been reproduced it in it either I believe this issue is limited to IE for now. Please let me know if you have any reason to think otherwise.

**Comment by zenkavi** [comment] 2016-02-18 22:31
Closing this issue because there are now more general issues ( #289 and #288) addressing the problems and there isn't a specific issue for this questionnaire left once those are resolved.

**Closed by zenkavi** 2016-02-18 22:31 UTC
Labels: IE_specific, questionnaire
